### ISSUE TITLE
DEDE改进问题

### ISSUE THREAD

**Issue by Open-Source-Chivalry** [dedetech/issues#14]
1，支持百万级数据静态与动态。
2，添加站点地图，站长自动收录提交，以及实用小工具。
3，添加外部框架小工具。
4，后台界面太丑，重做一下。

**Comment by llgoer** [comment]
1.这个我们会通过一些扩展实现；
2.站点地图工具，如果数据量不大，可以采用自由列表工具实现；
3.外部框架小工具是指？
4.后台界面接下来会稍微调整，但动静不大；
