### ISSUE TITLE
希望不再区分移动端和PC端，将m目录摒弃掉，模板pc和h5分为两个目录

### ISSUE THREAD

**Issue by Lopins** [dedetech/issues#15]
1. 希望不再区分移动端和PC端，自定义表单提交完成后跳转有影响
2. 将m目录摒弃掉
3. 模板方面 pc和h5分为两个目录

**Comment by llgoer** [comment]
我们提倡响应式布局，如果有更复杂的自适应需求，可以联系我

**Comment by zmpx** [comment]
同样希望不再区分移动端和PC端，在后台生成不用再分开生成了

**Comment by llgoer** [comment]
已经移除m相关文件
