### ISSUE TITLE
dedecms5.8 文章集 发布后无法修改缩略图；

### ISSUE THREAD

**Issue by shouhou-mip** [dedetech/issues#21]
检测后发现，article_edit.php 缺少对64位图片的处理，article_edit.html 没有对缩略图64位传递；
解决方法：
复制 
`<input type="hidden" id="litpic_b64" name="litpic_b64" value="">`
 粘贴在 article_edit.html 的 93 行附近
![image](https://user-images.githubusercontent.com/44076758/92353127-350d7080-f112-11ea-9102-8998f4a461f8.png)
复制
`    // 处理新的缩略图上传
    if ($litpic_b64 != "") {
        $data = explode( ',', $litpic_b64 );
        $ntime = time();
        $savepath = $ddcfg_image_dir.'/'.MyDate($cfg_addon_savetype, $ntime);
        CreateDir($savepath);
        $fullUrl = $savepath.'/'.dd2char(MyDate('mdHis', $ntime).$cuserLogin->getUserID().mt_rand(1000, 9999));
        $fullUrl = $fullUrl.".png";
        
        file_put_contents($cfg_basedir.$fullUrl, base64_decode( $data[ 1 ] ));

        // 加水印
        WaterImg($cfg_basedir.$fullUrl, 'up');
        $litpic = $fullUrl;
    }`
粘贴在article_edit.php `$litpic = GetDDImage('none', $picname, $ddisremote);`128行下面
![image](https://user-images.githubusercontent.com/44076758/92353291-89185500-f112-11ea-9f4e-1c360061dcca.png)

**Comment by llgoer** [comment]
已修正，感谢
