### ISSUE TITLE
建议最新版本能实现手机端静态化

### ISSUE THREAD

**Issue by xuerff** [dedetech/issues#22]
以前版本，移动端只要动态生成，如果需要静态化，还学要进行二开，希望开发人员在新版本能解决这个手机端静态化问题，谢谢！

**Comment by llgoer** [comment]
目前DedeCMSv58建议手机前端页面采用响应式布局，以适应多端，暂不考虑再增加手机页面静态化功能。
感谢您的建议，当前issues暂时先关闭。
