### ISSUE TITLE
关于织梦V5.8的更新建议

### ISSUE THREAD

**Issue by pxhcxx** [dedetech/issues#24]
一，去掉专题，强化TAG功能
理由：
1、专题页面包含标题、关键字、内容及相关的内容，而TAG也有以上的内容，两者的功能很多都重叠
2、TAG可以在文章中调用，很方便，而专题调用就不方便
3、现在很多大网站都放弃了专题。
4、专题的更新比TAG麻烦，专题需要点击生成，TAG则不需要，输入确定就自动生成了
5、专题有封面、有内容页，其实和栏目的原理差不多，如果把栏目的功能强化一下也可以单独用栏目开辟一个专题
建议：TAG功能可以设置自定义标题、缩略图、关键字、描述，以及调用栏目内容下指定的文章内容相关的信息，TAG现在显示还不能按栏目显示，如果一篇文章有两个TAG标签，那么在不同的栏目下不能同时显示。

二、将内容模型简化
理由：
1、目前网络的信息传播形式大概有文字、图片、音视频这几种形式，分类信息、小说、软件下载等功能其实可以用自定义字段来实现
2、模型做的多反而没有办法集中精力来做精，现在织梦主要是内容管理系统，而小说、软件下载、分类信息、视频、问答等模型有专门的开源软件，将精力分散并不利于织梦的发展
3、后期可以以插件的形式开放出这些功能

三、增加文章站内的相关性
理由：
1、今日头条等APP就是利用文章的相关性做站内推荐，其算法也是根据文章的属性来推荐相关的
2、一篇文章不只有同一个属性，当一篇文章的属性越多越丰富时，系统可推荐的文章就越多，通过用户的点击不断的优化更新推荐机制，令推荐更加的智能
3、文章相关性可读性高用户体验好，搜索引擎也会给予以很好的排名
4、目前网上的文章同质化很多，当文章质量一样时，能留住客户多点击就看谁推荐的内容是用户感兴趣的内容

**Comment by llgoer** [comment]
感谢您的建议，TAG在这个版本进行了少量优化，由于涉及到调整内容比较多，更多功能强化将在下个版本中继续进行。
由于目前调整开发工作量比较大，一些新功能特性将会在后续版本中进行完善。
