### ISSUE TITLE
关于dedecms 升级建议

### ISSUE THREAD

**Issue by xqd360** [dedetech/issues#25]
建议新增小程序功能，可以将网站打包成支持百度，微信，头条等主流的小程序，一个站点就可以接入到多平台，特别是百度，本身网站大多面对的还是做搜索引擎
建议新增公众号平台接入功能
建议重点优化移动端的相关支持，侧重移动端的功能与便利性，移动化时代织梦错过了太多了

**Comment by llgoer** [comment]
感谢您的建议
