### ISSUE TITLE
一些使用建议

### ISSUE THREAD

**Issue by kaeyuan** [dedetech/issues#27]
用dede老版本做的网站起码上百个了，最近刚刚下了5.8测试，根据和使用后台者常遇到的疑问，结合自己的体验，提出以下建议：
1-新编辑器界面好像不错，但是多图上传、附件上传、视频插入没有了？
   编辑器功能一定要简单易用醒目，**网站都是给小白、普通人、不懂代码的人用的。**
2-**文章排序功能，这个基本上每个使用者都会反馈的最大问题。**
   应该有一个全站默认的排序规则，（后台文章列表页可以看到这个值，调大小）。
3-手机版暂时没看到，这个肯定必须的吧。
   缺少移动端所有页面的静态生成功能。
   刚刚看了关闭问题，说删除m目录，提倡响应式布局。事实呢：一方面，响应式布局日落西山；另一方面，dede的目标大都是中小企业客户，基本上用不到响应式布局啊。相反，**m功能是非常受到欢迎的，做个投票，最少90%的人支持。**
   而且现在的响应式，大部分都是假响应式。pc、m代码放到一起判断宽度hide-show，根本称不上响应式。
4-文章多了更新加载都太慢，经常更新大半个小时。突然出错就前功尽弃。
5-建议看下织梦猫的插件。他们自己弄了一些挺不错的。一些精华的可以默认集成到dede里的https://www.dedemao.com/dedeplug/list_2_1.html
-------暂时想到这些，厚颜贴上，以供参考，感谢各位百忙之中操持。

**Comment by llgoer** [comment]
编辑器多图、附件在后续版本会完善
全站有一个sortrank默认排序，可以通过设定置顶时间来调整排序
移动端响应式布局倒是一个趋势，并不是没落，只是许多以前老站点无法更好的做适配呈现才更多采用响应式，不过动态访问确实是一个需求，在后续版本会进行完善
文章更新慢的问题在新版本中会进行一些优化，这一块在后续版本中会持续优化
插件模块在接下来版本中也会进行优化，争取建立一个比较完善的生态
感谢您的意见建议
