### ISSUE TITLE
加强安全性，增加H5，小程序，微信公众号对接

### ISSUE THREAD

**Issue by mengxuntianya** [dedetech/issues#8]
感谢大佬带来的这么好的程序，不过做站经常被搞，不更新了漏洞就一直在那，还有人不停地发现新漏洞，如果要重拾起来的话，请大佬不要放弃，一直关注更新功能。
      因为经常被挂马，在逐步向WP转，但是毕竟国外的东西不太适应国情。
      另外增加H5，小程序，微信公众号对接。

**Comment by mengxuntianya** [comment]
老的DEDE5.7的可以平滑更新到5.8。

**Comment by llgoer** [comment]
不会放弃，一步步来

**Comment by xue-jiqiao** [comment]
一直是大佬的粉丝，求一直更新，支持您！

**Comment by llgoer** [comment]
感谢，一路相随
